### ISSUE TITLE
Cannot Export SVG or PDF

### ISSUE THREAD

**Issue by kevinmyers** [arklumpus/TreeViewer#12]
I have a tree (newick format) that I've imported into TreeViewer. Whenever I try to export the tree as PDF or SVG, I get an error:

"Error while saving the SVG file: No attachment selected!"

I'm not sure what to try to get around this. I've never had this issue before and not sure what to do.

Here is the tree.nwk data:
(((((((iscR_protein_Eco_K12_MG1655:0.28290401,Shewanella:0.24067579)0.7540:0.13098450,Pseudomonas_aeruginosa_PAO1:0.19009611)0.9080:0.16061088,(Neisseria:0.44825208,Rhodobacter:0.58663179)0.4000:0.06135371)0.9640:0.34878359,(Cyanobacteria_Microcystis:0.19272268,Cyanobacteria_Synechocystis:0.34394328)0.9980:0.47179395)0.5820:0.22153197,(Deinococcus_radiodurans:0.38238652,(Clostridioides:0.54126126,Bacillus_subtitles:0.48034944)0.4340:0.19611611)0.4580:0.22838653)0.4180:0.16477862,Novosphingobium:0.81610562)0.2080:0.03889063,Streptomyces:0.80658385,(Termotoga:1.20374859,Zymo:1.08310660)0.6040:0.33290562);

**Comment by arklumpus** [comment]
Hi! The tree looks fine to me; I think you may have accidentally enabled a module (likely a _Further transformation_ module) that requires an attachment to be selected, without specifying an attachment.

You should be able to see this by opening the list of the Further transformations (`Further transformations` button in the `Modules` tab) or the list of Plot actions (`Plot actions` button in the same tab). If I'm correct, you should see one of the modules in the list with a yellow warning sign.

**Comment by kevinmyers** [comment]
Argh! That was it! Glad it was easy, but feel dumb for not seeing it! Thanks for your help!

**Comment by arklumpus** [comment]
No worries, glad you solved it!
