### ISSUE TITLE
Opening MCMCTree file

### ISSUE THREAD

**Issue by CarlisleEmily** [arklumpus/TreeViewer#13]
Hello, 

I'm trying to open a tree file (output from MCMCTree), but when I try to load it an error box pops up saying "An error has occurred while loading the file! Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')". 

I tried exporting it as a nexus file from FigTree and I can open that version of the tree file, but it loses all of the age estimate data in the process. Any ideas how I can get this to load? 

Many thanks,
Emily

**Comment by arklumpus** [comment]
Hi! Can you please upload or send me the tree file you're trying to open?

**Comment by arklumpus** [comment]
Hi Emily, I know we already addressed this privately, but I am just updating things here.

Files produced by MCMCtree are supported as of TreeViewer 2.1.0; there is also a [tutorial in the wiki](https://github.com/arklumpus/TreeViewer/wiki/Plotting-multiple-age-distributions) showing how to plot multiple age distributions produced by MCMCtree (as well as the fossil calibrations) on a single tree.

I am closing this, feel free to reopen or open a new issue if you still have questions!
