### ISSUE TITLE
How to make the "Scale axis" module's ticks not start at the tips?

### ISSUE THREAD

**Issue by jrom99** [arklumpus/TreeViewer#19]
I have a tree with samples from 2023 and root a few centuries ago, this tree has a time axis that I configured via "Reverse axes" + "Negative ages" + offset of 2023. The ticks have a spacing of 25, with start at 0 and end at the root height. I'd like to show the scale from the root to 2023, with the ticks appearing at `25*i` (ie: the first and last ticks are not at scale's edges) instead of at the current `2023 - 25*i` (ie: the last tick is at the scale's end).

![image](https://github.com/arklumpus/TreeViewer/assets/47498278/c89ae782-0f47-4272-86c3-e9b98ea0db79)

## System information:

TreeViewer version 2.2.0
OS: Ubuntu 23.10
DE: GNOME Shell 45.2

**Comment by arklumpus** [comment]
What if you set the offset to `2027` and the start to `-2`? In this way the rightmost tick will be at 2025.

Alternatively, if you don't want the future date, you can do this:
1. Figure out the age of the root node. Let's assume it's `1807`.
    * If you don't have this information, you can compute it using the `Compute node ages` _Further transformation module_.
2. In the scale axis, set these options:
    * Uncheck `Reverse axes`
    * Uncheck `Negative ages`
    * Set the offset to `1807` (or your root age)
    * Set the `Tick spacing` to `25`
    * Set the `Start` to `-7` (if you want the axis to start at 1800) or `18` (if you want it to start at 1825).
    * Set the `End` to `216` (i.e., `2023 - 1807`, with the appropriate root age)
This will make the axis start with a tick at the root end and end without a tick at the tips' end.

Does this work? In any case, either the start or the end tick must be aligned with the scale.

**Comment by jrom99** [comment]
Thanks, it worked!
