### ISSUE TITLE
Can't add FASTA attachment to Plot Alignment

### ISSUE THREAD

**Issue by Matt-BF** [arklumpus/TreeViewer#2]
Hi! First of all, great program! Very intuitive and easy to use.

I've had problems adding the Plot alignment module, when I click "select attachment" to get the FASTA alignment, nothing opens allowing me to select a file

PS: Program installed on Windows 10

**Comment by arklumpus** [comment]
Hi! Glad you like it!

You need to add the attachment first, by clicking on the green `+` button at the top left of the interface, next to `Attachments`. When you click on this button, the dialog should open, allowing you to select the file.

Then, in the _Plot alignment_ module, the attachment that you have just added should appear when you expand the box next to `FASTA alignment`.

**Comment by Matt-BF** [comment]
OK, that worked! Thanks! Didn't see the attachments button
