### ISSUE TITLE
How to make TreeViewer use dated tips?

### ISSUE THREAD

**Issue by jrom99** [arklumpus/TreeViewer#20]
I'm using a MCC tree obtained from a BEAST analysis with dated samples, it seems that the scale/branch lengths are out of sync with the dated tips (and maybe nodes as well). On Figtree, all tips that were sampled at the same date share the same x-coordinates, but the same doesn't happen for TreeViewer, how can I make it so that TreeViewer uses the correct x-coordinate?

## System information

TreeViewer version 2.2.0
OS: Ubuntu 23.10
DE: GNOME Shell 45.2

**Comment by jrom99** [comment]
I know this is the wrong place to ask, but how can I use the Math.Floor function within a "Format attribute..." window?

**Comment by arklumpus** [comment]
Hi, for the tree I am not 100% sure what you mean - if you can send me a screenshot or an example (either here or via e-mail) it would help! In any case, if TreeViewer is computing a consensus tree, you may want to make sure that the `Treat trees as clock-like` option in the parameters for the _Transformer module_ is enabled:

![image](https://github.com/arklumpus/TreeViewer/assets/32712606/4bd78f34-3c08-4235-84ec-006ffa82790b)

Normally, the program determines whether the trees are clock-like by checking whether the tips are all contemporaneous, but if you have dated samples you need to specify it manually.

For the `Math.Floor` function, you should use the fully qualified name `System.Math.Floor` (and then use `ToString` to convert it to a string, of course).

![image](https://github.com/arklumpus/TreeViewer/assets/32712606/fc754658-5e88-4d52-b040-dc54c8c29b36)

**Comment by jrom99** [comment]
>Normally, the program determines whether the trees are clock-like by checking whether the tips are all contemporaneous, but if you have dated samples you need to specify it manually.

I have a maximum clade credibility consensus tree built using TreeAnnotator, and it uses sequences sampled at different times. BEAST uses `height`/`height_median` attributes instead of the sampling year.

I took a screenshot using a tree from the BEAST time-stamped sequences analysis tutorial (https://beast.community/workshop_rates_and_dates) with FigTree on the left and TreeViewer on the right:

![image](https://github.com/arklumpus/TreeViewer/assets/47498278/4a9fdd32-baea-4d2f-9590-f614c4c1ec5e)

The sequence `1979_AY540481_CAREC797984_Trinidad` is placed further to the right than what would be expected considering its sampling date.

Thank you very much for the support, I don't know how to program in C#, but the code editor and sidebar options are extremely useful! And TreeViewer itself is versatile enough that I rarely need to use them, so I was having a bit of trouble dealing with the functions namespaces.

Tree file: [YFV_MCC.tree.txt](https://github.com/arklumpus/TreeViewer/files/14172825/YFV_MCC.tree.txt)

**Comment by jrom99** [comment]
>After this, Length will be equal to Length2 across the whole tree, which should now be displayed the way you wanted it.

Thank you very much, it worked!
