### ISSUE TITLE
Extend branches to fixed position

### ISSUE THREAD

**Issue by lxsteiner** [arklumpus/TreeViewer#23]
Is it possible to extend scaled branches to a common fixed position? When I extend branches now they all get extended by the same length (start X - end X), which makes them all end at variable positions. See below:
![image](https://github.com/arklumpus/TreeViewer/assets/70258378/b8db8f03-ffe3-4517-83ff-fb84e30e4d51)

Also I'm not sure if there's a better way to have node states and branch labels be all aligned at the same starting position with in a tree with scaled branches (e.g. left aligned), other than setting their `Position->Anchor->Origin` and moving them to the right side of the tree by setting a large `Position->Position->X`.

Thank you!

**Comment by arklumpus** [comment]
Yes, that is the correct way to set a fixed position for labels and node states.

For branch extensions, you need to do a similar thing: set the `End anchor` to `Origin`, and then set an appropriate value for the `End->X`.
