### ISSUE TITLE
Manually colouring nodes or  labels

### ISSUE THREAD

**Issue by AndresZT** [arklumpus/TreeViewer#24]
Hi!
First of all, great job for this amazing tool

I was wondering if there is a way to manually editing nodes and labels. I am doing a gene family tree in a group of 4 interspecific hybrids, and I want to colour nodes according to the genotype. Something like this manually coloured tree where dark red, blue, beige and pink indicate the genotype. (Red circles are orthogroups, just ignore it) 

Thanks! 
![CLC full tree color](https://github.com/arklumpus/TreeViewer/assets/74092534/caf9f477-ebcd-4aea-8ff1-8a615be3f628)

**Comment by arklumpus** [comment]
Hi, thank you for using TreeViewer!

Yes, you should be able to easily achieve this. Basically, you need to create a table where you assign a colour (in RGB hex format `#RRGGBB`) to each taxon, add it as an attachment to the plot, and then use the _Parse node states_ Further transformation module to load it.

Step by step instructions (if you already have the table, you can skip the first steps and directly add it as an attachment):

1. Press `CTRL+A` (`CMD+A` on macOS) to select the whole tree (or click on `Edit`>`Select root`).
2. Press `CTRL+ALT+C` (`CMD+OPT+C` on macOS, or click on `Edit`>`Copy`>`Copy attribute value at tips`) to copy an attribute at the tips of the tree; leave the default `Name` selected and click OK.
3. Now, in the `Attachment` tab, click on the bottom half of the `Add attachment` button, then select `Open spreadsheet editor`; a spreadsheet window should now open.
4. Click on the `Paste` button to paste the tip names into the spreadsheet. Widen the column header as necessary.
5. If I understand correctly, the genotype is encoded by the start of the name (e.g., `140rug`, `K5140`, etc). To make things easier, you can click on the `Sort` button to sort the names alphabetically (in this way, names belonging to the same genotype will be grouped together).
6. Select all cells in column B next to one of the genotypes, and click on the `Colour picker` button (or press `CTRL+SHIFT+C`/`CMD+SHIFT+C`). In the colour picker window, choose the colour you want for this genotype and click on OK. The RGB hex value of the colour will be entered in the cells you had selected.
7. Repeat for the other genotypes, then click on `OK` to close the spreadsheet window.
8. Enter a name for the attachment (e.g., `GenotypeColours`) and click on `OK`. Nothing should change for now.
9. Now, open the Further transformation module panel by clicking on `Modules`>`Further transformations`. Click on `Add module` and select the _Parse node states_ module.
10. Expand the options for the module you have added, and set the following values:
    * For the `Data file`, select the attachment you have created.
    * For the `Separator`, select `\t` (i.e., a tab). The default `\s` (any whitespace character) should work as well, unless you have spaces in your taxon names.
    * For the `Column header(s)` enter `Color` (US spelling).
11. Click on `Apply`. The plot should update and the tips should become coloured. If you click on tip to inspect its attributes, you should see a new `Colour` attribute has been added.

Tips:
* If you prefer, you can prepare the table in a "proper" spreadsheet software (e.g., Excel) and then paste it in TreeViewer's spreadsheet editor.
* You could also display the genotype as a node state (i.e., a coloured shape next to the tip), like in [this tutorial](https://github.com/arklumpus/TreeViewer/wiki/Displaying-character-states-on-a-tree) (ask if you need help!)
* If you want to highlight the orthogroups (or something else), you can use the `Highlight node` module (see [the answers here](https://github.com/arklumpus/TreeViewer/issues/7) and in particular the [video](https://github.com/arklumpus/TreeViewer/issues/7#issuecomment-973566790)), _but only if the thing you are highlighting is a monophyletic group_.

Let me know if you need any more help!

**Comment by AndresZT** [comment]
Thanks very much it worked very well!

now i have a further question on support and lenght values which i will ask in a different issue
