### ISSUE TITLE
Adding a label to a collapsed clade

### ISSUE THREAD

**Issue by mahdi-b** [arklumpus/TreeViewer#28]
Hi,
Is possible to add a visible label to a collapsed clade? Although I am able to change the name of the collapsed clade. I am unable to see it in the plot (see image below). 

Thank you,
M.

<img width="943" alt="image" src="https://github.com/arklumpus/TreeViewer/assets/3051521/a68e35e5-49b8-4c3a-a4df-3c16a680f257">

**Comment by arklumpus** [comment]
Hi! Yes, sure, the easiest way is:
* Instead of changing the `Name`, add the text for the label to a different attribute, e.g. `CollapsedName`
* Duplicate the `Labels` attribute (using the little button with two squares)
* In the duplicate, change the following settings:
    * The `Attribute` to `CollapsedName` (or whatever you called the new attribute)
    * Set `Show on` to `Internal nodes` (this ensures that the labels are shown, even though the attribute is set on an internal node)
    * Uncheck the `Exclude cartoon nodes` check box (this will show the label even though the node is collapsed)
    * Set `Anchor` to `Centre of leaves` (so that the label appears next to the "base" of the triangle, rather than at the "tip")
    * Changing the `Anchor` will have changed the value for the `X` position, so you will need to change this as well (the default is `5`).

I hope this solves the issue, let me know if you still have problems!

**Comment by mahdi-b** [comment]
Thank you, @arklumpus. 
For the sake of documenting the solution, the following:
`Duplicate the Labels attribute (using the little button with two squares)`
refers to the option under `Modules` -> `Plot actions`

<img width="1070" alt="Screenshot 2024-05-06 at 1 27 42 PM" src="https://github.com/arklumpus/TreeViewer/assets/3051521/1690a482-b9e3-47f5-8db8-1d3f47dae61f">
