### ISSUE TITLE
Export error with font attachment

### ISSUE THREAD

**Issue by klcym** [arklumpus/TreeViewer#31]
Dear Giorgio :

I want to import a font used to plot the tree, but TreeViewer error when it export the PDF format file.

![image](https://github.com/arklumpus/TreeViewer/assets/68457155/b11c637b-b2a3-4603-8605-a8b689c629dc)

![image](https://github.com/arklumpus/TreeViewer/assets/68457155/55da16c6-ccfe-4892-b027-d00cf2dae044)

I wonder how to solve this problem, thanks for your help.

**Comment by klcym** [comment]
[Deng.zip](https://github.com/arklumpus/TreeViewer/files/15315317/Deng.zip)

This is the font file.

**Comment by arklumpus** [comment]
Hi! Would you be able to please send me a tree file (in NEXUS or Binary format) that shows the problem? I tried creating a random tree and using your font, and it works fine for me...

[test.pdf](https://github.com/arklumpus/TreeViewer/files/15332681/test.pdf)

**Comment by klcym** [comment]
Thank you for your reply!

This is the tree, it includes Chinese character by encoding with UTF-8. I think it is the key of the problem.

[test.zip](https://github.com/arklumpus/TreeViewer/files/15332895/test.zip)

**Comment by arklumpus** [comment]
I see, thanks for pointing this out! I have fixed the problem, but I don't have my signing key right now. I will push an update to the `Export` module that solves this later today!

**Comment by klcym** [comment]
Thank you! That will help me a lot!

**Comment by arklumpus** [comment]
Sorry for the delay, I just pushed this. You should get a notification when you open TreeViewer in the next 24 hours or so, or you can manually update the `Export` module by opening the Module repository (there's a button in the `Modules tab`).

Let me know if you still have issues!
