### ISSUE TITLE
How to show node states separately

### ISSUE THREAD

**Issue by jdasfd** [arklumpus/TreeViewer#38]
Dear Author,
Hi! I am using the TreeViewer and it is an amazing tool that really really helpful in showing my tree! 
I am trying to use the excellent function of "Parse node states" and "Node states" to show all the result on my tree. Thanks to the very outstanding example by the way! 

![my_tree](https://github.com/arklumpus/TreeViewer/assets/55595834/2d24a2b3-ab15-4d56-bee6-ade40972484b)

I want to show node colors separately. I wonder if there is any way to only show a color on the tree, without showing other node states? Or I could pass more different attachment files so that I could make multiple layers? Maybe show or hide a layer?

Thanks again for the amazing tool! Really appreciate that.

**Comment by arklumpus** [comment]
Hi, I'm glad you're finding TreeViewer useful!

I think it should not be hard to achieve what you want, but I'm not sure I understand exactly what it is 😅

For example, would you like to only show the red circles, while hiding the green, yellow and blue ones? Like this:

![image](https://github.com/arklumpus/TreeViewer/assets/32712606/e124f7cc-65bd-42b9-b9eb-854d04abfefb)

**Comment by jdasfd** [comment]
Yes! That is exactly what I mean. I want to submit a file containing all information of different nodes, and I want to observe the distribution of node features on the tree by only showing one color at a time or showing different combinations of colors.
