### ISSUE TITLE
Linux installer can potentially delete whole root filesystem

### ISSUE THREAD

**Issue by lukas-val** [arklumpus/TreeViewer#4]
Hi,

in TreeViewer_setup.sh (which should be executed with sudo), one of the first steps just after user has had the chance to enter custom installation directory is to clean up said directory with the following command:
`rm -rf $prefix/TreeViewer`, where $prefix is either "/usr/lib" or whatever was provided by the user.

In case of a mistake, where user made a mistake and accidentally inserted a space, e.g. `/ home/user/bin` instead of `/home/user/bin`, this clean up would result in script executing `rm -rf / home/user/TreeViewer` and deletion of the whole root filesystem.

I would suggest at very least modifying clean up command by quoting the input `rm -rf "$prefix/TreeViewer"`, in this case `rm` would fail with invalid input.

I don't think it's safe to assume that this sort of mistake won't occur (it did to me... good thing I bypassed the sudo requirement).

Lukas

**Comment by arklumpus** [comment]
Hi, thanks for pointing this out! The installer does ask for confirmation before proceeding, but quoting the argument is definitely a good idea (even though I am sure that there will be some weird edge case in which it does not avoid the issue 😅).

I have fixed the install script and updated the current release to address this!
