### ISSUE TITLE
Fan layout

### ISSUE THREAD

**Issue by aleixcanalda** [arklumpus/TreeViewer#42]
Hello!
Thank you for the great tool!
I would like to plot my tree with a half fan layout (i.e. instead of a 360 degree circle, a 180 degree circle, figure attached).
![half-fan-1](https://github.com/user-attachments/assets/3e7dfb8c-fddc-4fba-b232-60384a5ec1a6)
Is there any way this is possible using your tool? I can't figure out how to do this.
Thanks!!

**Comment by arklumpus** [comment]
Hi! I'm sorry, I thought I replied to you last week, but I must not have clicked the submit button 😅

In any case, on Friday I pushed an update to the Circular coordinates module, which now allows you to specify a "Sweep angle". You can set it to 180° to get something like your plot, or use other values for different effects (e.g., if you set it to 270°, you can leave some space for the legend within the plot).

I hope this helps, let me know if you have any more questions!

**Comment by aleixcanalda** [comment]
Works like a charm, thank you so much!!
