### ISSUE TITLE
Branch Extension Wrong direction

### ISSUE THREAD

**Issue by asommer3** [arklumpus/TreeViewer#47]
Hello,

I am trying to add branch extensions to a tree but there are two lines that orient the branch extensions in the wrong direction. I believe this may be due to these two tips being highly similar. Is there a way to fix this issue for better visualization?

![Screenshot 2024-10-28 091912](https://github.com/user-attachments/assets/7bbb4dd5-01e7-48ad-99aa-ec24338a6c7a)

**Comment by arklumpus** [comment]
Hi, is the length of those branches exactly 0? If so, that would explain this behaviour...

I would suggest changing the branch length to a very small value that is larger than 0; in this way, you should be able to get the branch extensions to work correctly with an imperceptible change to the actual tree.

**Comment by asommer3** [comment]
Thank you! The branch lengths were exactly 0. Changing the branch length to 0.00001 fixed the issue

**Comment by asommer3** [comment]
Thank you! The branch lengths were exactly 0. Changing the branch length to 0.00001 fixed the issue

**Comment by asommer3** [comment]
Thank you! The branch lengths were exactly 0. Changing the branch length to 0.00001 fixed the issue
