### ISSUE TITLE
Is it possible to add circular clade highlights?

### ISSUE THREAD

**Issue by carlosmag** [arklumpus/TreeViewer#7]
Hello!
Is it possible to add circular clade highlights (example: [ggtree R package](https://yulab-smu.top/treedata-book/chapter5.html#highlight-clades))?

P.S. Unlike other tools, TreeViewer's search and navigation/zoom functionalities are fast!

**Comment by arklumpus** [comment]
Hi! If I understand what you mean, I think this is similar to what @Dichromatism was asking in #5.

I have now added three new modules to the repository that can be used to achieve this; you can install them by going to `Modules`>`Module repository` and then locating them in the respective tabs (you should also get a prompt to do so the next time you open TreeViewer after midnight):

* **Highlight node** is a _Plot action_ module that can highlight a single node.
* **Highlight selection** is a _Selection action_ module that highlights the selected node (by enabling the Highlight node module)
* **Highlights** is another _Plot action_ module that highlights multiple nodes based on the value of attributes. To use this, after enabling the module, you also need to add an attribute called `Highlight` containing the highlight colour (e.g. `Red`) to the nodes that you want to highlight.

With these modules, you can create something like this:

<p align="center">
<img src="https://user-images.githubusercontent.com/32712606/142343581-a679d81f-9718-4576-8c11-b5adfdb02cf7.png" height="375"> <img src="https://user-images.githubusercontent.com/32712606/142343583-7bacbf75-9895-459f-a732-58ed04218165.png" height="375">
</p>
<p align="center">
<img src="https://user-images.githubusercontent.com/32712606/142343584-4d1a9357-81c6-44d2-b26d-bbc45a2aa021.png" height="375">
</p>

Let me know if these work for you!

**Comment by carlosmag** [comment]
Thanks a lot for your effort! I am amazed on how much you could do in a short period of time.

Your images look great! However, I couldn't reproduce the new features in my tree.

![treeviewer_nodehighlight](https://user-images.githubusercontent.com/10491107/142443846-2c5a8564-ace2-4028-8197-383b9dd3ed85.png)
![treeviewer_afterplotactionsnodehighlight](https://user-images.githubusercontent.com/10491107/142443913-127d846a-669a-4a70-80a8-dd58dbc48d21.png)

After selecting a node and clicking 'Add plot action -> Highlight node', it produces a very big circle...
Am I doing something wrong here?

P.S. I restarted the program after installing the modules...

**Comment by carlosmag** [comment]
I found it!, thanks!

Is it possible to change highlighting color without resorting to code?

**Comment by arklumpus** [comment]
Yes, sure! If you expand the options for this module, you can just change the "Fill colour":

![image](https://user-images.githubusercontent.com/32712606/142502725-491b2800-2d50-4f49-83b5-118d68a31043.png)

You can also "play" with the other options to see how they affect the result - e.g. the stroke is set to a transparent colour by default, but if you change the "Stroke colour" (increasing the alpha value) the outline of the node will be drawn as well.

**Comment by carlosmag** [comment]
Thanks a lot! 
Need to play more with these options and the rest of the tool!

**Comment by arklumpus** [comment]
Happy to help, have fun! 😁

**Comment by carlosmag** [comment]
Is it possible to highlight the branch lines? Something like this:

![branchcolortree](https://user-images.githubusercontent.com/10491107/142515818-682a338c-c2e8-4a11-a029-549c96d680ee.png)

I guess it might work better for me than increasing transparency in node highlights...

**Comment by arklumpus** [comment]
If you want the node highlight to appear behind the tree, that is easy: you just have to open the modules panel and drag the "Highlight node" module above all the rest.

If you want to change the colour of a part of the tree, you can do it like this:
* Click on the node, this should open the selection panel on the right;
* In the selection panel, click on the "Attribute" button at the top;
* Click on the "Add attribute" button to add a new attribute, call it `Color` and set the new value to something like `Red` or `#FF0000`, then press OK. When you do this, the colour of the branch you selected should change (but the descendants should still be black).
* You can propagate the new attribute to all descendants by opening the "Further transformations" module panel (click on the "Modules" tab, then on "Further transformations"), expanding the options for the "Add attribute" module (this module was added when you created the "Color" attribute), and checking the "Apply recursively to all children" box.

Here is a clip showing how to do both these things:

https://user-images.githubusercontent.com/32712606/142518052-aea4b2a0-3c74-4bae-a5d2-79b237848431.mp4


I would recommend having a look at the [tutorials](https://github.com/arklumpus/TreeViewer/wiki/Workload-examples) in the [Wiki](https://github.com/arklumpus/TreeViewer/wiki): for example, [this section](https://github.com/arklumpus/TreeViewer/wiki/Drawing-an-alignment-with-the-tree#highlighting-the-sequence-groups) of the tutorial to draw a sequence alignment with the tree shows how to use a different colour for different parts of the tree.

**Comment by carlosmag** [comment]
It worked! I guess I am understanding better the mechanics of the program...

I proceeded to the _Group labels_ module, using the tutorial you provided (which is great!, by the way).
However, the labels appear only in the root of the tree and not as in the example shown in the help of the module for circular trees.

![grouplabels_treeviewer](https://user-images.githubusercontent.com/10491107/142657467-0585f411-c8e3-48ff-a163-74a3e738a5ea.png)

**Comment by arklumpus** [comment]
If you open the options of the _Group labels_ module, there is a setting called `Distance`: this determines the distance of the labels from the root node. You need to increase this value to move the labels to the outside of the tree (try different values and see where the labels move).

**Comment by carlosmag** [comment]
Thanks, it worked!

In the tree I am working it, there are some branches placed a bit far comparatively to the others. Only way to have labels for these groups is to massively increase `Distance`, which will lead to lots of empty space on the nodes closer to the root?

![grouplabels_distance](https://user-images.githubusercontent.com/10491107/142659398-87855dd5-af3f-4dbb-b2cc-a7eaabae4225.png)

Is there a way to place labels outside each specified group, or do I need to set branch lengths to none?

**Comment by arklumpus** [comment]
You can enable two (or more) separate instances of the _Group labels_ module and use a different distance for each. You would then set the label values in different attributes, so that each module only shows some labels (you can change the attribute that is shown by each module by changing the `Attribute` parameter).

Like this:

https://user-images.githubusercontent.com/32712606/142661407-8097ca43-02f4-4cc3-aa52-833197d69a17.mp4

**Comment by carlosmag** [comment]
Is it possible to add newline characters to node attributes? I've tried some combinations but it did work...
Alternatively, is it possible to rotate text? This is because I have few space to write text in some highlights, such as:

![newlinecharfortree](https://user-images.githubusercontent.com/10491107/142783696-c6c1c4fe-80ad-4eea-819c-58a7ee353d71.png)

P.S. Annotation experience has been great so far!

**Comment by arklumpus** [comment]
I'm glad to hear you've had success with the program!

Unfortunately, you can't have newlines in the labels. You also can't rotate the text in the _Group labels_ module, but you can rotate it in the _Labels_ module. To achieve something similar to the group labels effect, you should set the "Anchor" to `Origin` and the "Branch reference" to `Circular`; then by increasing the X coordinate of the `Position` you can move the label outside the tree, like this:

https://user-images.githubusercontent.com/32712606/142785741-87ad2152-e986-4365-9990-d3813073add4.mp4

Alternatively, you can use the _Text_ module (this lets you draw a single string of text that you specify in the module parameters rather than as an attribute on the tree).

The _Legend_ module does support newlines (it draws Markdown code), but it's probably overkill.

**Comment by carlosmag** [comment]
_Labels_ module tip did the trick!

Thank you for your amazing support throughout this process! 
I hope to cite TreeViewer in a paper in the coming months. Fingers crossed!

**Comment by arklumpus** [comment]
Great, good luck!
