### ISSUE TITLE
file input for tree manipulation

### ISSUE THREAD

**Issue by alexwu66666** [arklumpus/TreeViewer#9]
Hi there,

I am doing a phylogeny study and would like to use TreeViewer to generate the circular tree for publication, while I met some troubles for the tree file input format. May I ask if this software support the tree generated by MEGA X as input (.mtsx format)? If not, are there any available formats you may recommend?

Best regards,
Chao

**Comment by arklumpus** [comment]
Hi! Unfortunately, the MEGA .mtsx format is not currently supported.

I would be happy to add support for it, but I have not been able to find a specification for this format... I also could not find a way to download the source code for MEGA from their website (even though their latest paper says that it should be available).

Your best option is probably to use MEGA to export the tree to a Newick or Nexus file, which should be compatible with TreeViewer.

Let me know if you have any other issues!

**Comment by alexwu66666** [comment]
> Hi! Unfortunately, the MEGA .mtsx format is not currently supported.
> 
> 
> 
> I would be happy to add support for it, but I have not been able to find a specification for this format... I also could not find a way to download the source code for MEGA from their website (even though their latest paper says that it should be available).
> 
> 
> 
> Your best option is probably to use MEGA to export the tree to a Newick or Nexus file, which should be compatible with TreeViewer.
> 
> 
> 
> Let me know if you have any other issues!

Wow thank you for the information! I tried with .nwk format and it is okay.

Best regards,
Chao

**Comment by arklumpus** [comment]
Hi, I think we addressed the problem, so I am closing this - feel free to reopen or open another issue if you still have questions.
